name: "Solar System"

on:
    workflow_dispatch:
    push:
      branches:
        - main
        - 'feature/*'

env: 
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: $ {{ vars.MANGO_USERNAME }}
    MONGO_PASSWORD: $ {{ secrets.MONGO_PASSWORD }}
        
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/setup-node@v4

        - name: setup NodeJS Version - 20
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: install dependencies
          run:  |
            npm install
            working-directory: github-actions-solar-system
        - name: Unit Testing 
          run: |
            cd github-actions-solar-system
            npm test  
        - name: Archive Test result
          uses: actions/upload-artifact@v4
          with: 
            name: Mocha-Test-Result
            path: test-resuts.xml