name: solar-system workflow

on:
    workflow_dispatch:
    push:
      branches:
        - main
        - 'feature/*'
        
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/setup-node@v4

        - name: setup NodeJS Version - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install dependencies
          run:  |
            cd github-actions-solar-system
            npm install
        - name: Unit Testing 
          run: |
            cd github-actions-solar-system
            npm test  